class Interface:
    running = True
    def draw(self): ...
    def cleanup(self): ...
    def keyboard(self, key: int, press: bool, keycode: int): ...
    def mouse_move(self, x: int, y: int): ...
    def mouse_button(self, x: int, y: int, button: int, press: bool): ...
    def mouse_scroll(self, x: int, y: int, direction: int): ...
